config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin::Devise.config
  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'products#index'
  get 'autocomplete', to: 'products#complete', as: 'complete'

  resources :categories, only: :show do
    resources :products, only: %i[index show]
  end

  resources :products, only: %i[index show] do
    resources :comments, only: %i[create update destroy]
    resources :order_items, only: %i[create update destroy]
    get :search, on: :collection
  end

  resource :cart, only: %i[show update] do
    get :profile, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :subcategories, class_name: 'Category', foreign_key: 'parent_id', dependent: :destroy
  belongs_to :parent_category, class_name: 'Category', optional: true

  validates :name, presence: true

  def to_param
    "#{id}-#{name}".parameterize
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product

  after_initialize do
    self.rating ||= 0 if new_record?
  end

  scope :persisted, -> { where.not(id: nil) }

  validates_presence_of :body
  validates_uniqueness_of :user_id, scope: :product_id
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  enum status: %i[pending ordered canceled]
  after_initialize do
    self.status ||= :pending if new_record?
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :user
  belongs_to :order
  belongs_to :product

  after_initialize do
    self.quantity ||= 0 if new_record?
  end
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :comments
  has_many :order_items, dependent: :destroy
  

  mount_uploader :image, ImageUploader
  validates_presence_of :name, :price, :category

  def to_param
    "#{id}-#{name}".parameterize
  end

  def average_rating
    return 0.0 if comments.persisted.empty?

    comments.persisted.sum(&:rating).to_f / comments.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:github]
  has_many :order_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :email, presence: true
  
  validates :email, uniqueness: true

  validates :password, presence: true, on: :create
  validates :password, confirmation: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_order
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token, only: :github

  def authenticate_active_admin_user!
    authenticate_user!
    unless current_user.superadmin?
      flash[:alert] = 'Unauthorized Access!'
      redirect_to root_path
    end
  end

  def current_order
    Order.find_or_create_by(user: current_user, status: 'pending')
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @order_items = current_order.order_items
  end

  def update
    update_order_items_quantities
    current_order.update(total_price: params[:total_price].to_f, status: 'ordered')
    last_ordered_order = current_user.orders.ordered.last
    OrderMailer.complete_order_email(current_user, last_ordered_order).deliver_now
  end

  def profile
    @ordered_orders = current_user.orders.ordered.order(created_at: :desc).paginate(page: params[:page], per_page: 6)
  end

  private

  def update_order_items_quantities
    quantities_array = params[:quantities].to_ary
    current_order.order_items.each.with_index do |item, index|
      item.update(quantity: quantities_array[index].to_i)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    product_categories = @category.subcategories.map(&:id) << @category.id
    @products = SortProductsService.new(params, Product.where(category_id: product_categories).all, 3).call
    @categories = Category.where(parent_id: nil)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_product
  before_action :authenticate_user!, only: %i[create destroy update]

  def create
    @comment = @product.comments.create(comment_params.merge(user_id: current_user.id))

    if @comment.save
      flash[:success] = 'Comment successfully added!'
    else
      flash[:danger] = 'Something wrong, sorry!'
    end
    redirect_to product_path(@product)
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:success] = 'Comment successfully updated!'
    else
      flash[:danger] = 'Something wrong, sorry!'
    end
    redirect_to product_path(@product)
  end

  def destroy
    @comment = Comment.find params[:id]
    @comment.destroy
    flash[:danger] = 'Comment deleted!'
    redirect_to product_path(@product)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :rating, :product_id, :user_id)
  end

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_params, only: %i[update destroy]

  def create
    @order_item = current_order.order_items.find_or_create_by(product_id: params[:product_id], user: current_user)
    @order_item.update(quantity: @order_item.quantity + 1)
    session[:order_id] = current_order.id
    redirect_to :cart
  end

  def update
    @order_items = current_order.order_items
    redirect_to :cart
  end

  def destroy
    @order_item.destroy
    redirect_to :cart
  end

  private

  def set_params
    @order_item = current_order.order_items.find(params[:id])
    @order_items = current_order.order_items
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = SortProductsService.new(params, Product.all, 6).call
    @categories = Category.where(parent_id: nil)
  end

  def show
    @product = Product.find(params[:id])
    @comment = @product.comments.build
    @comments = @product.comments.where.not(id: nil)
  end

  def complete
    render json: Product.all.map(&:name)
  end

  def search
    @products = Product.where('name ILIKE ?', "%#{params[:q]}%").paginate(page: params[:page], per_page: 3)
    render :index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])
    sign_in_and_redirect @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def comment_author?(user, comment)
    return false if user.nil?

    true if user.id == comment.user_id
  end

  def blank_stars(rating)
    5 - rating
  end

  def allowed_to_comment(product)
    allowed_products = []
    current_user.order_items.uniq(&:product_id).each do |order_product|
      allowed_products << order_product.product_id
    end
    allowed_products.include?(product.id)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_empty_cart.html.erb
<div class="container">
  <div class="row w-100">
    <div class="col-lg-12 col-md-12 col-12 mt-5">
      <div class="card h-100">
        <div class="card-body">
          <h4 class="card-title text-center text-info">
            Your cart is empty
          </h4>
          <div class="row d-flex justify-content-center">
            <div class="col-6">
              <%= image_tag("https://thebigray.ru/images/empty-cart.png", class: "card-img-top") %>
            </div>
          </div>
        </div>
      </div>
      <%= link_to " Continue Shopping", root_path, class: "btn btn-info text-white py-4 d-flex justify-content-center" %>
    </div>
  </div>
</div>

app/views/carts/_modal_success_order.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header d-flex justify-content-center">
        <h2 class="modal-title text-success" id="exampleModalLongTitle">Thank you for order <i class="far fa-heart"></i></h2>
      </div>
      <div class="modal-body">
        <%= image_tag("https://www.herbcience.com/assets/img/cart_empty.png", class: "card-img-top") %>
      </div>
      <div class="modal-footer d-flex justify-content-center">
        <%= link_to " Continue Shopping", root_path, class: "btn btn-outline-info py-2 float-left" %>
        <%= link_to " View orders profile", profile_cart_path, class: "btn btn-outline-success py-2" %>
      </div>
    </div>
  </div>
</div>

app/views/carts/_pending_order.html.erb
<div class="container">
  <div class="row w-100">
    <div class="col-lg-12 col-md-12 col-12">
      <h3 class="display-5 mt-5 mb-2 text-center">Shopping Cart</h3>
      <p class="mb-5 text-center">
        <i class="text-info font-weight-bold"><%= @order_items.count %></i> items in your cart</p>
      <table id="shoppingCart" class="table table-condensed table-responsive">
        <thead>
        <tr>
          <th style="width:60%">Product</th>
          <th style="width:12%">Price $</th>
          <th style="width:10%">Quantity</th>
          <th style="width:16%"></th>
        </tr>
        </thead>
        <tbody>
        <% @order_items.each do |item| %>
          <tr class="order-item">
            <td data-th="Product">
              <div class="row">
                <div class="col-md-3 text-left">
                 
                </div>
                <div class="col-md-9 text-left mt-sm-2">
                  <h4><%= item.product.name %></h4>
                </div>
              </div>
            </td>
            <td data-th="Price" class="item-price"><%= item.product.price %></td>
            <td data-th="Quantity">
              <input type="number" class="form-control form-control-lg text-center item-quantity" min="1" value="<%= item.quantity %>">
            </td>
            <td class="actions" data-th="">
              <div class="text-right">
                <%= link_to(product_order_item_path(product_id: item.product_id, id: item.id),
                            method: :delete, class: "btn btn-white border-secondary bg-white btn-md mb-2") do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <div class="float-right text-right">
        <h4>Subtotal:</h4>
        <h2 style="font-size: 2.3em" id="total-price"></h2>
      </div>
    </div>
  </div>
  <div class="row mt-4 d-flex align-items-center mb-5">
    <div class="col-lg-9 col-sm-7 mb-3 mb-m-1 order-md-1 text-md-left">
      <i class="fas fa-arrow-left mr-2 text-info"><%= link_to " Continue Shopping", root_path, class: "text-info text-decoration-none" %></i>
    </div>
    <div class="col-lg-3 col-sm-5 order-md-2">
      <button type="button" id="create-order-button" class="btn btn-info mb-4 float-right btn-lg pl-5 pr-5">Create order</button>
    </div>
  </div>
  <button type="button" class="show-modal btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter"></button>
</div>

app/views/carts/profile.html.erb
<div class="container mt-5 pb-5">
  <% if @ordered_orders.count.zero? %>
    <div class="row w-100">
      <div class="col-lg-12 col-md-12 col-12 mt-5">
        <div class="card h-100">
          <div class="card-body">
            <h4 class="card-title text-center text-info">
              There is no orders yet
            </h4>
            <div class="row d-flex justify-content-center">
              <div class="col-6">
                <%= image_tag("https://www.seoclerk.com/assets/img/features/noorders.png", class: "card-img-top") %>
              </div>
            </div>
          </div>
        </div>
        <%= link_to " Continue Shopping", root_path, class: "btn btn-info text-white py-4 d-flex justify-content-center" %>
      </div>
    </div>
  <% end %>

  <div class="row d-flex justify-content-center">
    <div class="col-lg-9 mt-5 mb-5">
      <div class="row d-flex justify-content-center">
        <% @ordered_orders.each do |order|%>
          <div class="col-8 mb-4">
            <div class="card">
              <div class="card-body">
                <% order.order_items.each do |item|%>
                  <div class="row">
                    <div class="col-7 text-left"><%= item.product.name %></div>
                    <div class="col-5 text-right"><%= item.quantity %> x $<%= item.product.price %></div>
                  </div>
                <% end %>
                <div class="row mt-2">
                  <div class="col-7 text-left"><h5>Total:</h5></div>
                  <div class="col-5 text-right"><h5 class="card-title">$<%= order.total_price %></h5></div>
                </div>
              </div>
              <div class="card-footer">
                <small class="text-muted"><%= order.created_at.to_date %></small>
              </div>
            </div>
          </div>
        <% end %>
        <div class="col-lg-12 mt-5 mb-5">
          <%= will_paginate @ordered_orders, list_classes: %w(pagination justify-content-center mb-5) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
<section class="pt-5 pb-5">
  <% if @order_items.count.positive? %>
    <%= render 'carts/pending_order' %>
  <% else %>
    <%= render 'carts/empty_cart' %>
  <% end %>

  <%= render 'carts/modal_success_order' %>
</section>

app/views/categories/show.html.erb
<div class="container mt-5 pb-5">

  <div class="row">
    <div class="col-lg-3">
      <%= render 'shared/categories' %>
      <div class="row">

        <div class="col-12">
          <div class="form-row align-items-center">
            <%= form_with url: category_path, html: {class: "form-group"}, method: :get, local: true do |f| %>
              <div class="col-auto my-1">
                <label class="mr-sm-2" for="inlineFormCustomSelect">Sort products</label>
                <%= f.select :filter, %w[LowPrice HighPrice Alphabetical], class: "custom-select mr-sm-2",
                             id: "inlineFormCustomSelect" %>
              </div>
              <div class="col-auto my-1">
                <%= f.submit "Submit", class: 'btn btn-danger', type: "submit" %>
              </div>
            <% end %>
          </div>

          <div class="form-row align-items-center">
            <%= form_with url: category_path, html: {class: "form-group"}, method: :get, local: true do |f| %>
              <div class="col-auto my-1">
                <label class="mr-sm-2" for="inlineFormCustomSelect">Price range</label>

                <%= f.number_field :min, value: 0, class: "col-auto form-control mr-sm-2 my-1",
                                   placeholder: "min price", id: "inlineFormCustomSelect" %>

                <%= f.number_field :max, value: 1000,
                                   class: "col-auto form-control mr-sm-2 my-1",
                                   placeholder: "max price", id: "inlineFormCustomSelect" %>
              </div>

              <div class="col-auto my-1">
                <%= f.submit "Submit", class: 'mt-2 btn btn-danger', type: "submit" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-9">
     
      <div class="row">
        <%= render 'products/product' %>
        <div class="col-lg-12 mt-5 mb-5">
          <%= will_paginate @products, list_classes: %w(pagination justify-content-center mb-5) %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/comments/_comment_form.html.erb
<%= form_with model: [@product, comment] do |form| %>
  <%= form.hidden_field :product_id, value: @product.id, class: "form-control" %>

  <div class="field form_field">
    <%= form.text_area :body, class: "form-control comment-text-area" %>
  </div>

  <div class="form_field">
    <%= form.hidden_field :rating, class: "form-control rating-field" %>
  </div>

  <div class="actions mt-3">
    <%= form.submit "Comment", class: 'submit_form btn btn-outline-info text-dark d-inline-block float-right' %>
  </div>
<% end %>

app/views/comments/_stars_rating.html.erb
<div class="rating">
  <input id="item5" name="rating" type="radio"
         value="5" class="rating__check">
  <label for="item5" class="rating__star rating__star_choose"></label>

  <input id="item4" name="rating" type="radio"
         value="4" class="rating__check">
  <label for="item4" class="rating__star rating__star_choose"></label>

  <input id="item3" name="rating" type="radio"
         value="3" class="rating__check">
  <label for="item3" class="rating__star rating__star_choose"></label>

  <input id="item2" name="rating" type="radio"
         value="2" class="rating__check">
  <label for="item2" class="rating__star rating__star_choose"></label>

  <input id="item1" name="rating" type="radio"
         value="1" class="rating__check">
  <label for="item1" class="rating__star rating__star_choose"></label>
</div>

app/views/layouts/_footer.html.erb
<div class="footer py-2 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Store-X</p>
    <p class="m-0 text-center text-white">2020</p>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">

    <%= link_to "Store-X", root_path, class: "navbar-brand" %>

    <%= form_with url: search_products_path, class: "search_form form-inline ml-lg-5", method: :get, local: true do |f| %>
      <%= f.text_field :q, id: "search-product", class: "form-control mr-2", type: "search",
                       placeholder: "Search", data: { behavior: "autocomplete" } %>
      <%= f.submit "Search", class: 'btn btn-danger ml-2 my-2 my-sm-0', type: "submit" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to 'Admin Panel',  admin_root_path, class: "nav-link"%>
          </li>
          <li class="nav-item ml-lg-3">
            <%= link_to(profile_cart_path, class: "nav-link") do %>
              <i class="fas fa-book"></i>
            <% end %>
          </li>
          <li class="nav-item ml-lg-3">
            <%= link_to(cart_path, class: "nav-link") do %>
              <i class="fas fa-shopping-cart"></i>
            <% end %>
          </li>
          <li class="nav-item ml-lg-3">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store X</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/products/_lightbox.html.erb
<!-- Large modal -->
<button type="button" class="btn btn-primary" id="lightbox-button" data-toggle="modal" data-target=".bd-example-modal-lg"></button>

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
     
    </div>
  </div>
</div>

app/views/products/_product.html.erb
<% @products.each do |product| %>
  <div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
      <%= image_tag(product.image_url, class: "card-img-top") %>
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to product.name, product, class: "text-danger" %>
        </h4>
        <div class="row">
          <div class="col-6">
            <h5>$<%= product.price %></h5>
          </div>
          <div class="col-6">
            <%= link_to(product_order_items_path(product), method: :post, class: "text-danger float-right") do %>
              <i class="fas fa-shopping-basket"></i>
            <% end %>
          </div>
        </div>
        <p class="text-justify card-text"><%= product.description %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/products/index.html.erb
<div class="container mt-5 pb-5">

  <div class="row">

    <div class="col-lg-3">
      <%= render 'shared/categories' %>
      <div class="row">
        <div class="col-12">
          <div class="form-row align-items-center">
            <%= form_with url: products_path, html: {class: "form-group"}, method: :get, local: true do |f| %>
              <div class="col-auto my-1">
                <label class="mr-sm-2" for="inlineFormCustomSelect">Sort products</label>
                <%= f.select :filter, %w[LowPrice HighPrice Alphabetical], class: "custom-select mr-sm-2",
                             id: "inlineFormCustomSelect" %>
              </div>
              <div class="col-auto my-1">
                <%= f.submit "Submit", class: 'btn btn-danger', type: "submit" %>
              </div>
            <% end %>
          </div>

          <div class="form-row align-items-center">
            <%= form_with url: products_path, html: {class: "form-group"}, method: :get, local: true do |f| %>
              <div class="col-auto my-1">
                <label class="mr-sm-2" for="inlineFormCustomSelect">Price range</label>

                <%= f.number_field :min, value: 0, class: "col-auto form-control mr-sm-2 my-1",
                                   placeholder: "min price", id: "inlineFormCustomSelect" %>

                <%= f.number_field :max, value: Product.all.map(&:price).max.round,
                                   class: "col-auto form-control mr-sm-2 my-1",
                                   placeholder: "max price", id: "inlineFormCustomSelect" %>
              </div>

              <div class="col-auto my-1">
                <%= f.submit "Submit", class: 'mt-2 btn btn-danger', type: "submit" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-9">
      <%= render 'shared/carousel' %>
      <div class="row">
        <%= render 'products/product' %>
        <div class="col-lg-12 mt-5 mb-5">
          <%= will_paginate @products, list_classes: %w(pagination justify-content-center mb-5) %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/products/show.html.erb
<div class="container mt-5 pb-5">

  <div class="row">

    <div class="col-lg-3">
      <%= render 'shared/categories' %>
    </div>

    <div class="col-lg-9 my-4">
      <div class="row">
        <div class="col-12 mb-4">
          <div class="card h-100">
           
   <%= cl_image_tag(@product.image_url, class: "card-img-top") %>
 
            <div class="card-body">
              <h4 class="card-title">
                <%= @product.name %> ( <%= @product.average_rating  %> <i class="fas fa-star" style="color: #ffde00"></i>)
              </h4>
              <h5>$<%= @product.price %></h5>
              <p class="card-text text-justify"><%= @product.description %></p>
            </div>
          </div>
        </div>

        <div class="col-lg-7 py-5">
          <% if current_user.present? && allowed_to_comment(@product) %>
            <div class="card shadow">
              <div class="row">
                <div class="rating-stars col-12 my-3 pl-5">
                  <h6>Rate product:</h6>
                  <%= render 'comments/stars_rating' %>
                </div>
                <div class="col-12 pl-5 mb-3 pr-5">
                  <%= render 'comments/comment_form', product_id: @product.id, comment: @comment %>
                </div>
              </div>
            </div>
          <% end %>
        </div>

        <% @comments.each do |comment| %>
          <div class="col-lg-10">
            <div class="card shadow mb-5">
              <div class="card-header">
                <h6><%= comment.user.name %></h6>
              </div>

              <div class="card-body">
                <% comment.rating.times do %>
                  <i class="fas fa-star" style="color: #ffde00"></i>
                <% end %>
                <% blank_stars(comment.rating).times do %>
                  <i class="far fa-star" style="color: #e1e1e1"></i>
                <% end %>
                <p class="card-text mt-3"><%= comment.body %></p>
              </div>

              <% if comment_author?(current_user, comment) %>
                <div class="row">
                  <div class="toggle-edit-btn col-12 text-right pl-5 mb-3 pr-5">
                    <a class="text-dark" style="font-size: 1.5em; cursor: pointer">
                      <i class="far fa-edit"></i>
                    </a>
                    <%= link_to(product_comment_path(@product, comment),
                                method: :delete, class: "text-dark ml-3", style: "font-size: 1.5em") do %>
                      <i class="far fa-trash-alt"></i>
                    <% end %>
                  </div>
                  <div class="update-comment-form col-12 text-right pl-5 mb-3 pr-5">
                    <%= render 'comments/comment_form', comment: comment %>
                  </div>
                </div>
              <% end %>

            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
  <%= render 'products/lightbox' %>
</div>

app/views/shared/_categories.html.erb
<div class="list-group my-4">
  <% Category.where(parent_id: nil).each do |category| %>
    <div class="btn-group dropdown">
      <%= link_to category.name, category, class: "col-lg-7 col-sm-4 btn text-decoration-none text-left", id: category.id %>
      <button type="button" class="col-lg-3 col-sm-1 btn dropdown-toggle dropdown-toggle-split text-left" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropright</span>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
        <% category.subcategories.each do |subcategory| %>
          <%= link_to subcategory.name, subcategory, class: "dropdown-item", type: "button", id: subcategory.id %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>